global:
  scrape_interval: 15s 
  
  external_labels:
    monitor: 'nginx-monitor'

scrape_configs:  
  - job_name: 'prometheus'
    
    scrape_interval: 5s

    static_configs:
      - targets: ['$NGX_SERVER_IP:9113'] # NGINX VM

